AllCops:
  Exclude:
    - teasy.gemspec
    - 'vendor/**/*'
    - 'test/**/*'

# Setting the line length to a maximum of 80 chars.
LineLength:
  Enabled: true
  Max: 80
Documentation:
  Enabled: false
